fail_fast: false
default_language_version:
  python: python3.12
repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.16.8
    hooks:
      - id: ruff-check
        args: [--fix]
      - id: ruff-format

  - repo: https://github.com/zizmorcore/zizmor-pre-commit
    rev: v1.29.0
    hooks:
      - id: zizmor
        files: ^\.github/
        types: [file]
        pass_filenames: false
        args: ["--no-progress", ".github/workflows"]

  - repo: builtin
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
